version: "3.7"
services:
  publisher:
    #build:
    #  context: .
    image: nghdavid/publisher:latest
    container_name: publisher
    ports:
        - "3000:3000"
    env_file:
        - .env     # path to your .env file
    restart: always
